apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "tasks-pipeline"
    annotations:
          pipeline.alpha.openshift.io/uses: '[{"name": "tasks", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    source:
      type: "Git"
      git:
        uri: "http://gogs.myproject.svc.cluster.local:3000/rramalho/openshift-tasks"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: jenkins-pipeline.groovy
kind: List
metadata: []
